---
title: "Channel Islands"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(rmarkdown)
library(usmap)
library(data.table)
library(scales)
library(janitor)
```



### Samples 
```{r Samples, echo=FALSE, fig.height=3, message=FALSE, warning=FALSE}

world_map <- map_data("world")

cipop <- read_csv("cisites.csv") %>% mutate(group=case_when(year>1999 ~"aughts", TRUE ~ "eighties"))

ci <- cipop %>% filter(!(str_detect(name, "CA_")))

ca <- cipop %>% filter(str_detect(name, "CA_"))


ggplot() +
  geom_polygon(data = world_map, aes(x=long, y = lat, group = group), 
               fill = "gray95", color="gray40", linewidth=0.3) + 
  geom_point(data=ci, aes(x=long, y = lat, group), size=1) +
  coord_fixed(xlim = c(-120.5, -118.3),  ylim = c(32.7, 34.2)) +
  xlab("") + ylab("") +
  theme(panel.grid.minor=element_blank(),
        panel.grid.major = element_blank(),
        panel.background=element_rect(color="white",fill="white",linewidth = 0.5),
        axis.line=element_line(color="black"),
        axis.text=element_text(color="black"),
        axis.ticks=element_line(color="black")) 

subset <- c("SCZ05M","SRR7458269","SNI41F","SRR7458267")

cipop %>% filter(INDV %in% subset)


```

```{bash}
#!/bin/sh
#SBATCH --job-name=smcpp_SCZ05M
#SBATCH --output=/scratch1/marjanak/islands/logs/smcpp_SCZ05M_%a.out
#SBATCH --error=/scratch1/marjanak/islands/logs/smcpp_SCZ05M_%a.err
#SBATCH --time=30:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8000MB
#SBATCH --array=1-32
#SBATCH --mail-type=END,FAIL # notifications for job done & fail
#SBATCH --mail-user=marjanak@usc.edu


module purge
module load gcc/12.3.0
module load singularity/3.11.3


singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif vcf2smc grayfox_filtered.renameChroms.ACgr25_DPgr165lt500.vcf.gz SCZ05M_chr${SLURM_ARRAY_TASK_ID}.gf.smc.gz chr${SLURM_ARRAY_TASK_ID} Pop1:SCZ05M.grayfox
```


```{bash}

#!/bin/sh
#SBATCH --job-name=smcpp_SCZ05M_est
#SBATCH --output=/scratch1/marjanak/islands/logs/smcpp_SCZ05M_est.out
#SBATCH --error=/scratch1/marjanak/islands/logs/smcpp_SCZ05M_est.err
#SBATCH --time=30:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8000MB
#SBATCH --mail-type=END,FAIL # notifications for job done & fail
#SBATCH --mail-user=marjanak@usc.edu

module purge
module load gcc/12.3.0
module load singularity/3.11.3

singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif estimate 2e-8 --em-iterations 25 SCZ05M_chr*.gf.smc.gz -o SCZ05M

singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif plot SCZ05M_plot_gf.png SCZ05M/model.final.json 




singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif vcf2smc grayfox_filtered.renameChroms.ACgr25_DPgr165lt500.vcf.gz SCZ_SRR7458269/SRR7458269_chr1.gf.smc.gz chr1 Pop1:SRR7458269.grayfox  &> SCZ_SRR7458269/chr1.log




singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif estimate 2e-8 --em-iterations 25 --timepoints 500 1e5 SNI41F_chr*.gf.smc.gz -o SNI41F &> SNI41F_est.log





singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif estimate 2e-8 --em-iterations 25 SRR7458269_chr*.gf.smc.gz



singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif plot SCZ05M_plot10to1e7_gf.png model.final.json 

singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif plot SCZ05M_plot10to1e7_gf2.png model.final.json --knots

singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif estimate 2e-8 --em-iterations 25 --timepoints 10 1e7 SCZ05M_chr*.gf.smc.gz &> SCZ05M_est2.log




singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif estimate 2e-8 --em-iterations 25 SRR7458269_chr*.gf.smc.gz &> SRR7458269_est.log




singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif estimate 2e-8 --em-iterations 25 SRR7458267_chr*.gf.smc.gz &> SRR7458267_chr2_est.log


singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif estimate 2e-8 --em-iterations 25 SCZ05M_chr*.gf.smc.gz &> SCZ05M_est3.log





singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif estimate 2e-8 --em-iterations 25 --timepoints 10 1e7 scz_chr*.gf.smc.gz &> SCZ_two_mask.log



singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif plot scz_gf.png model.final.json 


singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif estimate 2e-8 --em-iterations 25 --timepoints 10 1e7 sni_chr*.gf.smc.gz --base sni &> SNI_two_mask.log



singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif plot sni_gf1988.png sni.final.json 




singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif cv 2e-8 --timepoints 10 1e7 sni_chr*.gf.smc.gz --base sni --cores 4 --folds 4 --spline cubic &> SNI_two_mask.log

singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif plot sni_gf_nomask.png sni.final.json 




singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif estimate 2e-8 --em-iterations 25 --timepoints 10 1e7 SCZ05M_chr*.gf.smc.gz --base SCZ05M &> SCZ05M_mask.log



singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif estimate 2e-8 --em-iterations 25 --timepoints 10 1e7 SRR7458269_chr*.gf.smc.gz --base SRR7458269 &> SRR7458269_mask.log

singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif plot SRR7458269_mask_gf.png SRR7458269.final.json 





singularity run -C --bind $PWD --pwd $PWD /project/jazlynmo_738/software/smcpp_latest.sif plot SCZ05M_mask_gf.png SCZ05M.final.json 




```



```{r}


plotcf <- read_csv("~/plot_cf.csv") %>% mutate(plot_num=as.character(plot_num)) %>% filter(!(x==0)) %>% filter(x<1e8 & x>0.45)

scaleFUN <- function(x) sprintf("%.0f", x)


ggplot(plotcf)+
  geom_line(aes(x=x,y=y,group=plot_num)) + 
  scale_y_continuous(trans = "log",labels=scaleFUN)+ 
  scale_x_continuous(trans = "log",labels=scaleFUN)+
  labs(title="San Nicolas Islands (n=3) mapped to Canfam3.1",
       caption = "2e-8 mutation rate and 1 year generation",
       subtitle = "ten runs",
      x ="Years", y = "Effective Population Size") +
  theme_classic() +
  theme(axis.text=element_text(color="black", size=11))

ggsave("~/sni_cf.png", width=6, height = 5, units="in")




plotcf1 <- read_csv("~/plot_cf_chr1.csv") %>% mutate(plot_num=as.character(plot_num)) %>% filter(!(x==0)) %>% filter(x<1e8 & x>0.45)



ggplot(plotcf1)+
  geom_line(aes(x=x,y=y,group=plot_num)) + 
  scale_y_continuous(trans = "log",labels=scaleFUN)+ 
  scale_x_continuous(trans = "log",labels=scaleFUN)+
  labs(title="San Nicolas Islands (n=3) mapped to Canfam3.1 CHR 1",
       caption = "2e-8 mutation rate and 1 year generation",
       subtitle = "ten runs",
      x ="Years", y = "Effective Population Size") +
  theme_classic() +
  theme(axis.text=element_text(color="black", size=11))

ggsave("~/sni_cf_chr1.png", width=6, height = 5, units="in")





plotgf <- read_csv("~/plot_gf.csv") %>% mutate(plot_num=as.character(plot_num)) %>% filter(!(x==0)) %>% filter(x<1e8 & x>0.1)

ggplot(plotgf)+
  geom_line(aes(x=x,y=y,group=plot_num)) + 
  scale_y_continuous(trans = "log",labels=scaleFUN)+ 
  scale_x_continuous(trans = "log",labels=scaleFUN)+
  labs(title="San Nicolas Islands (n=3) mapped to Grayfox",
       caption = "2e-8 mutation rate and 1 year generation",
       subtitle = "ten runs",
      x ="Years", y = "Effective Population Size") +
  theme_classic() +
  theme(axis.text=element_text(color="black", size=11))

ggsave("~/sni_gf.png", width=6, height = 5, units="in")




plotgfit <- read_csv("~/plot_gf_nmax.csv") %>% mutate(plot_num=as.character(plot_num)) %>% filter(x>1 & x<1e6)



plotgfit2 <- read_csv("~/plot_gf_nmax2.csv") %>% mutate(plot_num=as.character(plot_num)) %>% filter(x>1 & x<1e6) %>% mutate(plot_num="final")

ggplot()+
  geom_line(data=plotgfit,aes(x=x,y=y,group=plot_num), color="gray") + 
  geom_line(data=plotgfit2,aes(x=x,y=y,group=plot_num), color="black") + 
  scale_y_continuous(trans = "log",labels=scaleFUN)+ 
  scale_x_continuous(trans = "log",labels=scaleFUN)+
  labs(title="San Nicolas Islands (n=3) mapped to Grayfox",
       caption = "2e-8 mutation rate and 1 year generation",
      x ="Years", y = "Effective Population Size") +
  theme_classic() +
  theme(axis.text=element_text(color="black", size=11)) + facet_wrap(~plot_num)

ggsave("~/sni_gf_nmax_facet.png", width=7, height = 7, units="in")





```

